# Generated by Django 5.0.6 on 2024-07-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="phone",
            field=models.IntegerField(default=0),
        ),
    ]
