# Generated by Django 5.0.6 on 2024-07-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_orders_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="amount",
            field=models.IntegerField(default=0),
        ),
    ]
